# Generated by Django 4.2.4 on 2023-09-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_cnfrepeatability_expense_income_transactionstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionrepeatability',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='idStatus',
            field=models.ForeignKey(default=1, on_delete=models.SET(2), to='transactions.transactionstatus'),
        ),
    ]
