# Generated by Django 4.2.4 on 2023-09-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transactionrepeatability_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionrepeatability',
            name='date',
            field=models.IntegerField(default=0),
        ),
    ]
