# Generated by Django 4.2.4 on 2023-09-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_transactionrepeatability_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactioncategory',
            name='categoryColor',
            field=models.CharField(max_length=20),
        ),
    ]
