# Generated by Django 4.2.4 on 2023-09-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_transactioncategory_categorycolor'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionAccountTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
            ],
        ),
    ]
