# Generated by Django 4.2.4 on 2023-09-28 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_transactionaccounttypes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionaccount',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.transactionaccounttypes'),
        ),
    ]
