# Generated by Django 4.2.4 on 2023-10-03 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_alter_transactionaccount_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='dueDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='dueDate',
            field=models.DateField(null=True),
        ),
    ]
